In [1]:
import numpy as np

In [2]:
#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.
ar = np.arange(0,30).reshape(15,2)
ar

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [11]:
#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
ar1=np.random.randint(0,100,60).reshape(15,2,-1)
ar1.shape
ar1.ndim

3

In [21]:
#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.
ar2= np.random.randint(0,10,20).reshape(5,4)
ar2
ar3 =ar2.reshape(-1)
ar3.shape
ar3.ndim

1

In [23]:
#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.
ar4 = np.random.randint(0,10,20).reshape(5,4)
for i in ar4:
    print(i)
    
for i in np.nditer(ar4):
    print(i)

[8 8 0 7]
[0 5 4 2]
[2 0 8 5]
[3 1 4 1]
[5 7 0 4]
8
8
0
7
0
5
4
2
2
0
8
5
3
1
4
1
5
7
0
4


In [37]:
#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
# 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
#Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. 
#İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi
ar5 = np.arange(5,35,5)
ar6 = np.arange(1,7)
ar5[1]+ar6[1]
ar5[1]-ar6[1]
ar5[1]*ar6[1]
ar5[1]/ar6[1]

5.0

In [39]:
#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.
ar7 = np.random.randint(0,100,10)
ar7.sum()
ar7.max()
ar7.var()
ar7.std()

28.54540243191537

In [41]:
#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun.
#Ardından bu iki array'i concatenate ederek ekrana yazdırın.
ar8 = np.arange(0,20)
ar9= np.arange(500,531)
np.concatenate([ar8,ar9],axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

In [44]:
#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. 
#Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun.
#Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.
ar0 = np.arange(15,51)
ar10 = np.arange(10,101)
ar11 = np.concatenate([ar0,ar10])
ar11[25:50]=888
ar11

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [50]:
#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve
#320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. 
#Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

ar12 = np.arange(0,40).reshape(8,5)
ar13 = np.arange(320,360).reshape(8,5)
ar14 = np.concatenate([ar12,ar13],axis=0)
ar15= np.concatenate([ar12,ar13],axis=1)
ar15
ar14

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

In [53]:
#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın.
#Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

ar16 = np.concatenate([ar12,ar13],axis=2)
ar17 = np.stack([ar12,ar13],axis=2)
#stackleme yapılabilirken concatenate işlemi belli seviyelerde yapılamaz hata verir
ar17

In [56]:
#11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun.
#Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.
ar18=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(ar18==5)


(array([ 5, 13], dtype=int64),)

In [57]:
#12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.
np.where(ar18%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

In [58]:
#13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.
np.where(ar18>4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

In [59]:
#14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.
np.where(ar18//5)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

In [70]:
#15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin
ar19 =np.arange(85,100)
np.random.choice(ar19)

97

In [85]:
#16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.
ar20 =np.arange(10,100)
sayac = 0
b = np.random.choice(ar20,9)
b.reshape(3,3)

array([[43, 89, 78],
       [91, 31, 10],
       [74, 29, 60]])

In [77]:
ar20 =np.arange(10,100)
b = np.random.choice(ar20)
b

96

In [80]:
#17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.
ar22 = np.arange(35,60)
np.random.choice(ar22)

46

In [82]:
#18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.
ar23 = np.array([3, 8, 10, 53,10,8,3,53,10,3]).reshape(2,5)
ar23

array([[ 3,  8, 10, 53, 10],
       [ 8,  3, 53, 10,  3]])